### ISSUE TITLE
Update to v1.0.18

### ISSUE THREAD

**Issue by Geod24** [Geod24/libsodiumd#4]
Released May 31st: https://github.com/jedisct1/libsodium/releases/tag/1.0.18-RELEASE
Required for Schnorr signatures

**Comment by denizzzka** [comment]
Done in https://github.com/Geod24/libsodiumd/pull/5

**Comment by denizzzka** [comment]
> Required for Schnorr signatures

What name of symbols what provides this functionality? I am not checked it.

**Comment by Geod24** [comment]
> crypto_core_ed25519_scalar_mul
